 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: AEROSONDE                                                   
     # Surfaces =   4
     # Strips   =  44
     # Vortices = 352

  Sref =  1.0000       Cref = 0.21130       Bref =  2.9380    
  Xref = 0.70000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case: -unnamed-                               

  Alpha =   0.00000     pb/2V =   0.00000     p'b/2V =   0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =   0.00000     r'b/2V =   0.00000

  CXtot =  -0.00481     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.00201
  CZtot =  -0.35436     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.35436
  CDtot =   0.00481
  CDvis =   0.00000     CDind =   0.00481
  CLff  =   0.35372     CDff  =   0.00479    | Trefftz
  CYff  =   0.00000         e =    0.9629    | Plane  
 
   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000
 
 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.613504    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.196476
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.075293
 y  mom.  Cm |    Cma =  -1.573813    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.053773

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000001    CLq =   7.612626    CLr =   0.000000
 y  force CY |    CYp =  -0.092579    CYq =   0.000000    CYr =   0.163120
 x' mom.  Cl'|    Clp =  -0.390607    Clq =   0.000000    Clr =   0.095462
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -20.408558    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.036484    Cnq =   0.000000    Cnr =  -0.047118

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.005873   CLd3 =   0.000000
 y  force CY |   CYd1 =   0.000328   CYd2 =   0.000000   CYd3 =  -0.003228
 x' mom.  Cl'|   Cld1 =   0.000968   Cld2 =   0.000000   Cld3 =   0.000044
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =  -0.027954   Cmd3 =   0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000012   Cnd2 =   0.000000   Cnd3 =   0.001158
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =   0.000089 CDffd3 =   0.000000
 span eff.   |    ed1 =   0.000000    ed2 =   0.013835    ed3 =   0.000000
 
 

 Neutral point  Xnp =   0.162029

 Clb Cnr / Clr Cnb  =   0.691103    (  > 1 if spirally stable )
