 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: AEROSONDE                                                   
     # Surfaces =   4
     # Strips   =  44
     # Vortices = 352

  Sref =  1.0000       Cref = 0.21130       Bref =  2.9380    
  Xref = 0.70000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.14061     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00006     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =   0.00001     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =  -0.00000
  CDtot =   0.00006
  CDvis =   0.00000     CDind =   0.00006
  CLff  =   0.00010     CDff  =   0.00005    | Trefftz
  CYff  =   0.00000         e =    0.0000    | Plane  

   aileron         =   0.00000
   elevator        =   5.84689
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.628212    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.194377
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.066171
 y  mom.  Cm |    Cma =  -1.465764    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.057420

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   7.605300    CLr =  -0.000000
 y  force CY |    CYp =  -0.134229    CYq =  -0.000001    CYr =   0.128481
 x' mom.  Cl'|    Clp =  -0.392969    Clq =   0.000000    Clr =   0.010688
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -19.378464    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.001469    Cnq =   0.000000    Cnr =  -0.042622

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.005799   CLd3 =   0.000000
 y  force CY |   CYd1 =   0.000316   CYd2 =   0.000000   CYd3 =  -0.003185
 x' mom.  Cl'|   Cld1 =   0.000973   Cld2 =   0.000000   Cld3 =   0.000037
 y  mom.  Cm |   Cmd1 =  -0.000000   Cmd2 =  -0.027192   Cmd3 =   0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000055   Cnd2 =  -0.000000   Cnd3 =   0.001126
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000043 CDffd3 =  -0.000000
 span eff.   |    ed1 =   0.000000    ed2 =   0.000829    ed3 =  -0.000000



 Neutral point  Xnp =   0.155363

 Clb Cnr / Clr Cnb  =   4.595471    (  > 1 if spirally stable )
