 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Geometry                                                    
     # Surfaces =   2
     # Strips   =  16
     # Vortices = 128

  Sref = 0.18000       Cref = 0.28000       Bref = 0.63000    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =   0.00000     p'b/2V =   0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =   0.00000     r'b/2V =   0.00000

  CXtot =   0.00000     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =   0.00000     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.00000
  CDtot =   0.00000
  CDvis =   0.00000     CDind =   0.00000
  CLff  =   0.00000     CDff  =   0.00000    | Trefftz
  CYff  =   0.00000         e =    0.0000    | Plane  
 
 
 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   2.761431    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =   0.000000
 x' mom.  Cl'|    Cla =   0.000000    Clb =   0.000000
 y  mom.  Cm |    Cma =  -0.683935    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.000000

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   5.279872    CLr =   0.000000
 y  force CY |    CYp =   0.000000    CYq =   0.000000    CYr =   0.000000
 x' mom.  Cl'|    Clp =  -0.210830    Clq =   0.000000    Clr =   0.000000
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -2.764571    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =   0.000000    Cnq =   0.000000    Cnr =   0.000000

 Neutral point  Xnp =   0.069349
