/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeometryEditor.java
 *
 * Created on 19-jul-2011, 20:28:06
 */

package com.abajar.crrcsimeditor;

import com.abajar.crrcsimeditor.panels.SurfaceEditor;

/**
 *
 * @author hfreire
 */
public class GeometryEditor extends javax.swing.JFrame {

    final private CRRCsimEditor controller;
    /** Creates new form GeometryEditor */
    public GeometryEditor(CRRCsimEditor controller ){
        this.controller = controller;
        initComponents();
    }

    public void addSurface(){
        SurfaceEditor surfaceEditor = new SurfaceEditor(this.controller);
        this.add(surfaceEditor);
        surfaceEditor.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
