/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeometryEditor.java
 *
 * Created on 19-jul-2011, 20:28:06
 */

package com.abajar.crrcsimeditor;

import javax.swing.table.DefaultTableColumnModel;
import com.abajar.crrcsimeditor.avl.AVLGeometry;
import java.util.EnumSet;
import com.abajar.crrcsimeditor.avl.AVL;
import com.abajar.crrcsimeditor.avl.geometry.Body;
import com.abajar.crrcsimeditor.avl.geometry.Control;
import com.abajar.crrcsimeditor.avl.geometry.Section;
import com.abajar.crrcsimeditor.avl.geometry.Surface;
import com.abajar.crrcsimeditor.avl.mass.Mass;
import com.abajar.crrcsimeditor.avl.mass.MassObject;
import com.abajar.crrcsimeditor.avl.view.SelectorMutableTreeNode;
import com.abajar.crrcsimeditor.avl.view.SelectorMutableTreeNode.ENABLE_BUTTONS;
import com.abajar.crrcsimeditor.avl.view.table.AVLModelTableFactory;
import javax.swing.table.TableColumn;
import javax.swing.tree.DefaultTreeModel;
import static java.util.EnumSet.of;

/**
 *
 * @author hfreire
 */
public class GeometryEditor extends javax.swing.JFrame {

    final private CRRCsimEditor controller;
    /** Creates new form GeometryEditor */
    public GeometryEditor(CRRCsimEditor controller ){
        this.controller = controller;
        initComponents();
    }

    private DefaultTreeModel getTreeModel(){
        AVL avl = this.controller.avl;
        
        SelectorMutableTreeNode avlNode = new SelectorMutableTreeNode(avl);
        SelectorMutableTreeNode geometryNode = createSelectorMutableTreeNode(avl.getGeometry(),of(ENABLE_BUTTONS.ADD_SURFACE, ENABLE_BUTTONS.ADD_MASS));

        for(Surface surf : avl.getGeometry().getSurfaces()){
            SelectorMutableTreeNode surfNode = createSurfaceTreeNode(surf);
            geometryNode.add(surfNode);

            for(Section section:surf.getSections()){
                SelectorMutableTreeNode sectionNode = createSectionTreeNode(section);
                surfNode.add(sectionNode);

                for(Control control:section.getControls()){
                    SelectorMutableTreeNode controlNode = createControlTreeNode(control);
                    sectionNode.add(controlNode);
                }
            }
        }
        
        for(Body body : avl.getGeometry().getBodies()){
            SelectorMutableTreeNode bodyNode = createSelectorMutableTreeNode(body, of(ENABLE_BUTTONS.NONE));
            geometryNode.add(bodyNode);
        }
        

//        for(Mass mass:avl.getMass().getMass()){
//            SelectorMutableTreeNode mNode = new SelectorMutableTreeNode(mass);
//            massNode.add(mNode);
//        }
        
        avlNode.add(geometryNode);
//        avlNode.add(massNode);
        return new DefaultTreeModel(avlNode);
    }

    private SelectorMutableTreeNode createSelectorMutableTreeNode(Object object, EnumSet<ENABLE_BUTTONS> options){
        SelectorMutableTreeNode smTreeNode = new SelectorMutableTreeNode(object, options);
        for(Mass mass : ((MassObject)object).getMasses()){
            smTreeNode.add(createMassTreeNode(mass));
        }
        return smTreeNode;
    }

    public void updateAVLTree(){
        this.avlTree.setModel(this.getTreeModel());
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        avlTree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        modelPropertiesTable = new javax.swing.JTable();
        addSurfaceButton = new javax.swing.JButton();
        addSectionButton = new javax.swing.JButton();
        addControlButton = new javax.swing.JButton();
        addMassButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        avlTree.setModel(this.getTreeModel());
        avlTree.setName("avlTree"); // NOI18N
        avlTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                avlTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(avlTree);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        modelPropertiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        modelPropertiesTable.setName("modelPropertiesTable"); // NOI18N
        jScrollPane2.setViewportView(modelPropertiesTable);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.abajar.crrcsimeditor.CRRCsimEditor.class).getContext().getResourceMap(GeometryEditor.class);
        addSurfaceButton.setText(resourceMap.getString("addSurfaceButton.text")); // NOI18N
        addSurfaceButton.setEnabled(false);
        addSurfaceButton.setName("addSurfaceButton"); // NOI18N
        addSurfaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSurfaceButtonActionPerformed(evt);
            }
        });

        addSectionButton.setText(resourceMap.getString("addSectionButton.text")); // NOI18N
        addSectionButton.setEnabled(false);
        addSectionButton.setName("addSectionButton"); // NOI18N
        addSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSectionButtonActionPerformed(evt);
            }
        });

        addControlButton.setText(resourceMap.getString("addControlButton.text")); // NOI18N
        addControlButton.setEnabled(false);
        addControlButton.setName("addControlButton"); // NOI18N
        addControlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addControlButtonActionPerformed(evt);
            }
        });

        addMassButton.setText(resourceMap.getString("addMassButton.text")); // NOI18N
        addMassButton.setEnabled(false);
        addMassButton.setName("addMassButton"); // NOI18N
        addMassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMassButtonActionPerformed(evt);
            }
        });

        deleteButton.setText(resourceMap.getString("deleteButton.text")); // NOI18N
        deleteButton.setEnabled(false);
        deleteButton.setName("deleteButton"); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addSurfaceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSectionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addControlButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSurfaceButton)
                            .addComponent(addSectionButton)
                            .addComponent(addControlButton)
                            .addComponent(addMassButton)
                            .addComponent(deleteButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avlTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_avlTreeValueChanged
        SelectorMutableTreeNode treeNode = (SelectorMutableTreeNode)evt.getPath().getLastPathComponent();

        EnumSet<ENABLE_BUTTONS> options = treeNode.getOptions();
        addSurfaceButton.setEnabled(options.contains(ENABLE_BUTTONS.ADD_SURFACE));
        addSectionButton.setEnabled(options.contains(ENABLE_BUTTONS.ADD_SECTION));
        addControlButton.setEnabled(options.contains(ENABLE_BUTTONS.ADD_CONTROL));
        addMassButton.setEnabled(options.contains(ENABLE_BUTTONS.ADD_MASS));
        deleteButton.setEnabled(options.contains(ENABLE_BUTTONS.DELETE));
        showModelProperties(treeNode.getUserObject());
}//GEN-LAST:event_avlTreeValueChanged

    private void addSurfaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSurfaceButtonActionPerformed
        SelectorMutableTreeNode treeNode = (SelectorMutableTreeNode)this.avlTree.getSelectionPath().getLastPathComponent();
        Surface newSurface = this.controller.createSurfaceFor((AVLGeometry)treeNode.getUserObject()) ;
        ((DefaultTreeModel)this.avlTree.getModel()).insertNodeInto(createSurfaceTreeNode(newSurface), treeNode, treeNode.getChildCount());
    }//GEN-LAST:event_addSurfaceButtonActionPerformed

    private void addSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSectionButtonActionPerformed
        SelectorMutableTreeNode treeNode = (SelectorMutableTreeNode)this.avlTree.getSelectionPath().getLastPathComponent();
        Section newSection = this.controller.createSectionFor((Surface)treeNode.getUserObject()) ;
        ((DefaultTreeModel)this.avlTree.getModel()).insertNodeInto(createSectionTreeNode(newSection), treeNode, treeNode.getChildCount());
    }//GEN-LAST:event_addSectionButtonActionPerformed

    private void addControlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addControlButtonActionPerformed
        SelectorMutableTreeNode treeNode = (SelectorMutableTreeNode)this.avlTree.getSelectionPath().getLastPathComponent();
        Control newControl = this.controller.createControlFor((Section)treeNode.getUserObject()) ;
        ((DefaultTreeModel)this.avlTree.getModel()).insertNodeInto(createControlTreeNode(newControl), treeNode, treeNode.getChildCount());
    }//GEN-LAST:event_addControlButtonActionPerformed

    private void addMassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMassButtonActionPerformed
        SelectorMutableTreeNode treeNode = (SelectorMutableTreeNode)this.avlTree.getSelectionPath().getLastPathComponent();
        Mass newMass = this.controller.createMassFor((MassObject)treeNode.getUserObject()) ;
        ((DefaultTreeModel)this.avlTree.getModel()).insertNodeInto(createMassTreeNode(newMass), treeNode, treeNode.getChildCount());
    }//GEN-LAST:event_addMassButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        SelectorMutableTreeNode deleteTreeNode = (SelectorMutableTreeNode) this.avlTree.getSelectionPath().getLastPathComponent();
        SelectorMutableTreeNode parentTreeNode = (SelectorMutableTreeNode) this.avlTree.getSelectionPath().getParentPath().getLastPathComponent();
        deleteTreeNodeAndObject(parentTreeNode, deleteTreeNode);
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addControlButton;
    private javax.swing.JButton addMassButton;
    private javax.swing.JButton addSectionButton;
    private javax.swing.JButton addSurfaceButton;
    private javax.swing.JTree avlTree;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable modelPropertiesTable;
    // End of variables declaration//GEN-END:variables

    private void showModelProperties(Object userObject) {
        this.modelPropertiesTable.setModel(AVLModelTableFactory.createTableModel(userObject));
    }

    private void createColumn(DefaultTableColumnModel tableModel, String name){
       TableColumn tc =  new TableColumn();
       tc.setHeaderValue(name);
       tableModel.addColumn(tc);
    }

    private SelectorMutableTreeNode createSectionTreeNode(Section section) {
        return createSelectorMutableTreeNode(section, of(ENABLE_BUTTONS.ADD_CONTROL, ENABLE_BUTTONS.ADD_MASS, ENABLE_BUTTONS.DELETE));
    }

    private SelectorMutableTreeNode createSurfaceTreeNode(Surface surf){
        return createSelectorMutableTreeNode(surf, of(ENABLE_BUTTONS.ADD_SECTION, ENABLE_BUTTONS.ADD_MASS, ENABLE_BUTTONS.DELETE));
    }

    private SelectorMutableTreeNode createControlTreeNode(Control control) {
        return createSelectorMutableTreeNode(control, of(ENABLE_BUTTONS.ADD_MASS, ENABLE_BUTTONS.DELETE));
    }

    private SelectorMutableTreeNode createMassTreeNode(Mass mass) {
        return new SelectorMutableTreeNode(mass, of(ENABLE_BUTTONS.DELETE));
    }

    private void deleteTreeNodeAndObject(SelectorMutableTreeNode parentTreeNode, SelectorMutableTreeNode deleteTreeNode){
        ((DefaultTreeModel)this.avlTree.getModel()).removeNodeFromParent(deleteTreeNode);

        if(deleteTreeNode.getUserObject().getClass().equals(Mass.class)){
            ((MassObject)parentTreeNode.getUserObject()).getMasses().remove((Mass)deleteTreeNode.getUserObject());
        }else if(deleteTreeNode.getUserObject().getClass().equals(Surface.class)){
            ((AVLGeometry)parentTreeNode.getUserObject()).getSurfaces().remove((Surface)deleteTreeNode.getUserObject());
        }else if(deleteTreeNode.getUserObject().getClass().equals(Section.class)){
            ((Surface)parentTreeNode.getUserObject()).getSections().remove((Section)deleteTreeNode.getUserObject());
        }else if(deleteTreeNode.getUserObject().getClass().equals(Control.class)){
            ((Section)parentTreeNode.getUserObject()).getControls().remove((Control)deleteTreeNode.getUserObject());
        }

    }
}
